POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o vídeo node",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/17a6c9c7-0b28-430f-95f6-aefd017ab893
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/17a6c9c7-0b28-430f-95f6-aefd017ab893
