POST https://node-do-zero-0zu9.onrender.com/videos
Content-Type: application/json

{
    "title": "Primeiro vídeo do canal",
    "description": "Deixa o like e se inscreve",
    "duration": 600
}

###

GET https://node-do-zero-0zu9.onrender.com/videos
//?search=node

###

PUT https://node-do-zero-0zu9.onrender.com/videos/115509ff-9301-4f5f-8e00-0930a189cccc
Content-Type: application/json

{
    "title": "vai ser apagado",
    "description": "dá dislike",
    "duration": 180
}

###

DELETE https://node-do-zero-0zu9.onrender.com/videos/115509ff-9301-4f5f-8e00-0930a189cccc
